### ISSUE TITLE
Add headless CMS

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-docs#1]
Not sure where we landed on this discussion, so lets pick it back up again here

**Comment by jahabeebs** [comment]
@pi0neerpat I looked into Netlify CMS, Forestry, and Tina (the successor of Forestry). I still think spinning up GitHub codespaces whenever a non-technical person needs to add something to the docs might be the best option from what I've found:

1) Netlify CMS requires some special configuration if we want to use it w/Vercel (https://ironeko.com/posts/how-to-install-netlify-cms-on-vercel) and it would still be using Netlify for login. It would be $20 per member per month.

2) Forestry is $30/month for 5 members and the next tier up is $750/month. Forestry is going to be deprecated once Tina is at the same level so it probably doesn't make sense to start with something they're planning to deprecate.

3) Tina costs $30/month for 3 users and the next tier is $600/month for 10 users. There is no self-hosted version of Tina currently. This might be a good solution once they allow self-hosting?

If we go w/codespaces I would add to the docs how to spin up a codespaces instance for non-technical people and it would basically just be create codespace -> yarn install -> yarn start -> add new page to X folder using markdown (they would be able to see what it looks like while editing) -> commit changes via UI -> stop codespace. With this we can create a dedicated branch for a codespace that can be started and stopped so that whenever a change is committed we can see it and bring it in as a PR (...or they could just commit directly to main) 

What do you think?

**Comment by pi0neerpat** [comment]
Sounds good. Let's proceed with codespaces then

**Comment by jahabeebs** [comment]
@pi0neerpat added documentation here https://github.com/UseKeyp/usekeyp-docs/pull/6 feel free to review
